#!/usr/bin/python3
import os
import json
import re

conf = json.load(open("/home/lukas/.ev3-paths/cconf.json", "r"))
loadpath = conf["Config"]["loadpath"]
savepath = conf["Config"]["savepath"]
classname = conf["Config"]["classname"]
allfiles = os.listdir(loadpath)
files = []
for file in allfiles:
    if(".rppf" in file):
        files.append(loadpath+file)

for x in range(len(files)):
    print(str(x) + ": compiling...")
    prog_str = conf["Config"]["shebang"] + "\n\n"
    imports = conf["Config"]["Imports"]
    for module in imports:
        prog_str = prog_str + "from " + module["from"] + " import " + module["import"] + "\n"

    rclass = conf["Class"]
    prog_str = prog_str + classname + " = " + rclass["name"] + "("
    for i in range(len(rclass["Constructor"])):
        if(i < len(rclass["Constructor"]) - 1):
            prog_str = prog_str + str(conf["Config"]["Ports"][rclass["Constructor"][i]]) + ","
        else:
            prog_str = prog_str + str(conf["Config"]["Ports"][rclass["Constructor"][i]]) + ")\n"

    file = open(files[x], "r")
    for line in file:
        for method in rclass["Methods"]:
            if(method["match"] in line):
                prog_str = prog_str + classname + "." + method["name"] + "("
                for i in range(len(method["Parameters"])):
                    if(i < len(method["Parameters"]) - 1):
                        if(method["Parameters"][i] != "_"):
                            prog_str = prog_str + str(conf["Config"]["Constants"][method["Parameters"][i]]) + ","
                        else:
                            prog_str = prog_str + re.findall("(?<=" + method["match"] + ")(.*?)(?=" + method["match"] + ")", line)[0] + ","
                    else:
                        if(method["Parameters"][i] != "_"):
                            prog_str = prog_str + str(conf["Config"]["Constants"][method["Parameters"][i]]) + ")\n"
                        else:
                            prog_str = prog_str + re.findall("(?<=" + method["match"] + ")(.*?)(?=" + method["match"] + ")", line)[0] + ")\n"
    file.close()
    open(savepath + "run_" + str(x) + ".py", "w").write(prog_str)
    print(str(x) + ": compiled ✔")
